Repository clusterio/clusterio, pull requests merged in 2024-12, with the labels that each got.

#703 Add connect to server button to web UI using steam launch api
  README.md
  packages/web_ui/src/components/InstanceList.tsx
  packages/web_ui/src/components/InstanceViewPage.tsx
  packages/web_ui/src/util/instance.ts
Labels: Feature: Minor

#705 Recreate instance's required subfolders on startup
  packages/host/src/Host.ts
  packages/host/src/Instance.ts
Labels: Type: Bug

#704 In 2.0, icon_size is optional with a default of 64 - fixes #699
  packages/host/src/export.ts
Labels: Type: Bug, Factorio 2.0

#708 Use Get-Process instead of wmic on windows
  packages/host/src/Instance.ts
Labels: Type: Bug

#711 Expand compat to 0.17
  packages/create/templates/common/module/control.lua
  packages/host/modules/clusterio/api.lua
  packages/host/modules/clusterio/compat.lua
  packages/host/modules/clusterio/impl.lua
  packages/host/modules/clusterio/module.json
  plugins/inventory_sync/module/get_script_data.lua
  plugins/inventory_sync/module/inventory_sync.lua
  plugins/research_sync/module/sync.lua
Labels: Feature: Patch, Release: Next

#709 Add bidirectional sync to admin and ban list
  packages/controller/src/HostConnection.ts
  packages/host/modules/clusterio/impl.lua
  packages/host/src/Instance.ts
  packages/lib/src/config/definitions.ts
  packages/lib/src/data/messages_instance.ts
  packages/lib/src/plugin.ts
  test/host/Instance.js
  test/integration/clusterio.js
  test/integration/instance.js
  test/lib/config/migrations.js
Labels: Feature: Minor, Release: Next
