Repository clusterio/clusterio, pull requests merged in 2025-04, with the labels that each got.

#742 Improve error page with social links
  packages/controller/src/routes.ts
  packages/web_ui/src/components/ErrorPage.tsx
  packages/web_ui/src/images/console-error-edge.png
  packages/web_ui/src/pages.tsx
Labels: Feature: Patch

#741 Add bulk user actions (Import/Export/Restore)
  packages/controller/src/ControlConnection.ts
  packages/ctl/src/commands.ts
  packages/lib/src/data/messages_user.ts
  packages/lib/src/link/messages.ts
  packages/lib/src/permissions.ts
  packages/web_ui/src/components/SiteLayout.tsx
  packages/web_ui/src/components/UsersPage.tsx
  test/integration/clusterio.js
Labels: Feature: Minor

#747 Add config cloning on instance creation
  packages/controller/src/ControlConnection.ts
  packages/ctl/src/commands.ts
  packages/lib/src/config/classes.ts
  packages/lib/src/data/messages_instance.ts
  packages/web_ui/src/components/InstancesPage.tsx
  test/integration/clusterio.js
Labels: Feature: Minor

#749 Fix incorrect use of Array.splice
  packages/host/src/Instance.ts
Labels: Type: Bug

#743 Add button to download ctl config
  packages/web_ui/src/components/SiteLayout.tsx
  packages/web_ui/src/components/UsersPage.tsx
  packages/web_ui/src/util/save_file.ts
Labels: Feature: Patch

#746 Add log filters to web ui
  .eslintrc.js
  packages/lib/src/data/composites.ts
  packages/lib/src/data/messages_controller.ts
  packages/web_ui/src/components/ControllerPage.tsx
  packages/web_ui/src/components/HostViewPage.tsx
  packages/web_ui/src/components/InstanceViewPage.tsx
  packages/web_ui/src/components/LogConsole.tsx
  packages/web_ui/src/util/websocket.ts
Labels: Feature: Patch

#748 Add config option for console logging
  packages/host/src/Instance.ts
  packages/host/src/server.ts
  packages/lib/src/config/definitions.ts
  test/integration/clusterio.js
Labels: Feature: Minor

#753 Support quality and ghosts for power armor equipment
  packages/host/modules/clusterio/serialize.lua
Labels: Type: Bug

#755 Remove `phin` without introducing new dependencies
  packages/create/create.js
  packages/create/package.json
  plugins/player_auth/package.json
  plugins/player_auth/test/plugin.js
  test/controller/routes.js
  test/integration/create.js
  test/lib/ModStore.test.js
Labels: Feature: Refactor
